# General CAN Bus Decode Configuration
program: "CKPT_ECU_Comm_Test_PN12345678"
version: "V1.001"
author: "FirstName LastName"
date: "2025-09-26"

# Cockpit part numbers this config applies to
cockpit_PN:
  - 12345678

# CAN message definitions (grouped by CAN ID)
# start_byte, start_bit both start from 0

can_signals:
  - can_id: 0x111
    description: "Body Control Status"
    parameters:
      - name: "Vehicle_Power_Mode"
        start_byte: 6                             
        start_bit: 0
        bit_length: 2
        decode_type: "stateEncoded"
        values:
          0: "OFF"
          1: "ACC"
          2: "RUN"
          3: "CRANK"

      # - name: "Ignition_Voltage"
        # start_byte: 2
        # start_bit: 0
        # bit_length: 8
        # decode_type: "linear"
        # calculation:
          # a: 0.1   # scaling
          # b: 0.0   # offset

  - can_id: 0x200
    description: "Body_Information_1"
    parameters:
      - name: "Windshield_Wiper_Switch_Status"
        start_byte: 2
        start_bit: 0
        bit_length: 2
        decode_type: "stateEncoded"
        values:
          0: "OFF"
          1: "INTERMITTENT"
          2: "LOW"
          3: "HIGH"