# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'airspring_filling.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_airspring(object):
    def setupUi(self, airspring):
        airspring.setObjectName("airspring")
        airspring.resize(1433, 786)
        self.pushButton_wakeup_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_wakeup_indicator.setGeometry(QtCore.QRect(490, 63, 60, 60))
        self.pushButton_wakeup_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_wakeup_indicator.setText("")
        self.pushButton_wakeup_indicator.setObjectName("pushButton_wakeup_indicator")
        self.label = QtWidgets.QLabel(airspring)
        self.label.setGeometry(QtCore.QRect(80, 70, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(airspring)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(airspring)
        self.label_3.setGeometry(QtCore.QRect(70, 250, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(airspring)
        self.label_4.setGeometry(QtCore.QRect(70, 340, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(airspring)
        self.label_5.setGeometry(QtCore.QRect(70, 420, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(airspring)
        self.label_6.setGeometry(QtCore.QRect(70, 500, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(airspring)
        self.label_7.setGeometry(QtCore.QRect(70, 570, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(airspring)
        self.label_8.setGeometry(QtCore.QRect(70, 640, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(airspring)
        self.label_9.setGeometry(QtCore.QRect(70, 710, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.pushButton_testpresenter__indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_testpresenter__indicator.setGeometry(QtCore.QRect(490, 150, 60, 60))
        self.pushButton_testpresenter__indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color:gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_testpresenter__indicator.setText("")
        self.pushButton_testpresenter__indicator.setObjectName("pushButton_testpresenter__indicator")
        self.pushButton_sessionctrl_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_sessionctrl_indicator.setGeometry(QtCore.QRect(490, 240, 60, 60))
        self.pushButton_sessionctrl_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_sessionctrl_indicator.setText("")
        self.pushButton_sessionctrl_indicator.setObjectName("pushButton_sessionctrl_indicator")
        self.pushButton_readinfo_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_readinfo_indicator.setGeometry(QtCore.QRect(490, 330, 60, 60))
        self.pushButton_readinfo_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_readinfo_indicator.setText("")
        self.pushButton_readinfo_indicator.setObjectName("pushButton_readinfo_indicator")
        self.pushButton_readpressure_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_readpressure_indicator.setGeometry(QtCore.QRect(490, 410, 60, 60))
        self.pushButton_readpressure_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_readpressure_indicator.setText("")
        self.pushButton_readpressure_indicator.setObjectName("pushButton_readpressure_indicator")
        self.pushButton_frontspring_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_frontspring_indicator.setGeometry(QtCore.QRect(490, 480, 60, 60))
        self.pushButton_frontspring_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_frontspring_indicator.setText("")
        self.pushButton_frontspring_indicator.setObjectName("pushButton_frontspring_indicator")
        self.pushButton_checkfrontfill_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton_checkfrontfill_indicator.setGeometry(QtCore.QRect(490, 550, 60, 60))
        self.pushButton_checkfrontfill_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton_checkfrontfill_indicator.setText("")
        self.pushButton_checkfrontfill_indicator.setObjectName("pushButton_checkfrontfill_indicator")
        self.pushButton__checkrearfill_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton__checkrearfill_indicator.setGeometry(QtCore.QRect(490, 630, 60, 60))
        self.pushButton__checkrearfill_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton__checkrearfill_indicator.setText("")
        self.pushButton__checkrearfill_indicator.setObjectName("pushButton__checkrearfill_indicator")
        self.pushButton__readresult_indicator = QtWidgets.QPushButton(airspring)
        self.pushButton__readresult_indicator.setGeometry(QtCore.QRect(490, 700, 60, 60))
        self.pushButton__readresult_indicator.setStyleSheet("QPushButton {\n"
"    border-radius: 30px;\n"
"    border-style: outset;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
"        );\n"
"    padding: 5px;\n"
"    background-color: gray;\n"
"\n"
"    }\n"
"\n"
"")
        self.pushButton__readresult_indicator.setText("")
        self.pushButton__readresult_indicator.setObjectName("pushButton__readresult_indicator")
        self.label_10 = QtWidgets.QLabel(airspring)
        self.label_10.setGeometry(QtCore.QRect(580, 520, 91, 41))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(airspring)
        self.label_11.setGeometry(QtCore.QRect(690, 520, 91, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(airspring)
        self.label_12.setGeometry(QtCore.QRect(580, 670, 91, 41))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(airspring)
        self.label_13.setGeometry(QtCore.QRect(690, 670, 91, 41))
        self.label_13.setObjectName("label_13")
        self.textBrowser_datadisplay = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_datadisplay.setGeometry(QtCore.QRect(810, 70, 611, 691))
        self.textBrowser_datadisplay.setPlaceholderText("")
        self.textBrowser_datadisplay.setObjectName("textBrowser_datadisplay")
        self.pushButton_startfill = QtWidgets.QPushButton(airspring)
        self.pushButton_startfill.setGeometry(QtCore.QRect(50, 10, 211, 51))
        self.pushButton_startfill.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_startfill.setObjectName("pushButton_startfill")
        self.textBrowser_airtankpressure = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_airtankpressure.setEnabled(True)
        self.textBrowser_airtankpressure.setGeometry(QtCore.QRect(580, 420, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_airtankpressure.setFont(font)
        self.textBrowser_airtankpressure.setMarkdown("")
        self.textBrowser_airtankpressure.setObjectName("textBrowser_airtankpressure")
        self.textBrowser_LFpressure = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_LFpressure.setEnabled(True)
        self.textBrowser_LFpressure.setGeometry(QtCore.QRect(580, 560, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_LFpressure.setFont(font)
        self.textBrowser_LFpressure.setMarkdown("")
        self.textBrowser_LFpressure.setPlaceholderText("")
        self.textBrowser_LFpressure.setObjectName("textBrowser_LFpressure")
        self.textBrowser_RFpressure = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_RFpressure.setEnabled(True)
        self.textBrowser_RFpressure.setGeometry(QtCore.QRect(690, 560, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_RFpressure.setFont(font)
        self.textBrowser_RFpressure.setMarkdown("")
        self.textBrowser_RFpressure.setPlaceholderText("")
        self.textBrowser_RFpressure.setObjectName("textBrowser_RFpressure")
        self.textBrowser_RRpressure = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_RRpressure.setEnabled(True)
        self.textBrowser_RRpressure.setGeometry(QtCore.QRect(690, 710, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_RRpressure.setFont(font)
        self.textBrowser_RRpressure.setMarkdown("")
        self.textBrowser_RRpressure.setPlaceholderText("")
        self.textBrowser_RRpressure.setObjectName("textBrowser_RRpressure")
        self.textBrowser_LRpressure = QtWidgets.QTextBrowser(airspring)
        self.textBrowser_LRpressure.setEnabled(True)
        self.textBrowser_LRpressure.setGeometry(QtCore.QRect(580, 710, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser_LRpressure.setFont(font)
        self.textBrowser_LRpressure.setMarkdown("")
        self.textBrowser_LRpressure.setPlaceholderText("")
        self.textBrowser_LRpressure.setObjectName("textBrowser_LRpressure")

        self.retranslateUi(airspring)
        QtCore.QMetaObject.connectSlotsByName(airspring)

    def retranslateUi(self, airspring):
        _translate = QtCore.QCoreApplication.translate
        airspring.setWindowTitle(_translate("airspring", "Form"))
        self.label.setText(_translate("airspring", "唤醒模块"))
        self.label_2.setText(_translate("airspring", "发送Test Presenter"))
        self.label_3.setText(_translate("airspring", "进入扩展模式"))
        self.label_4.setText(_translate("airspring", "读取零件号/DTC/MEC"))
        self.label_5.setText(_translate("airspring", "读取储气罐压力值"))
        self.label_6.setText(_translate("airspring", "储气罐给前空悬气囊分气"))
        self.label_7.setText(_translate("airspring", "确认前囊分气完成"))
        self.label_8.setText(_translate("airspring", "储气罐给后空悬气囊分气"))
        self.label_9.setText(_translate("airspring", "读取分气完成后气压并记录"))
        self.label_10.setText(_translate("airspring", "左前气囊压力值"))
        self.label_11.setText(_translate("airspring", "右前气囊压力值"))
        self.label_12.setText(_translate("airspring", "左后气囊压力值"))
        self.label_13.setText(_translate("airspring", "右后气囊压力值"))
        self.pushButton_startfill.setText(_translate("airspring", "开始加注"))
        self.textBrowser_airtankpressure.setHtml(_translate("airspring", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_airtankpressure.setPlaceholderText(_translate("airspring", "储气罐压力值"))
        self.textBrowser_LFpressure.setHtml(_translate("airspring", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_RFpressure.setHtml(_translate("airspring", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_RRpressure.setHtml(_translate("airspring", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.textBrowser_LRpressure.setHtml(_translate("airspring", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
